'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
\\[\
$username\
$hostname\
\\]\
$directory\
$git_branch\
$cmd_duration\
$fill\
(\
$bun\
$c\
$cmake\
$dart\
$dotnet\
$golang\
$gradle\
$java\
$kotlin\
$lua\
$nodejs\
$package\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
-)\
$container\
$os\
$battery\
$time\
$linebreak
$character\
"""

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[cmd_duration]
min_time = 0
format = '\([$duration]($style)\)'

[username]
show_always = true
format = '[$user]($style)'

[hostname]
format = '@[$hostname$ssh_symbol]($style)'
ssh_symbol = '(ssh)'

[directory]
format = '\[[$path]($style)[($read_only)]($read_only_style)\]'
read_only = '!'

[git_branch]
format = '\([$symbol$branch(:$remote_branch)]($style)\)'
symbol = 'git:'

[fill]
symbol = '-'

[bun]
format = '\([$symbol$version]($style)\)'
symbol = 'bun:'
version_format = '${raw}'

[c]
format = '\([$symbol($name:)$version]($style)\)'
symbol = 'c:'
version_format = '${raw}'

[cmake]
format = '\([$symbol$version]($style)\)'
symbol = 'cmk:'
version_format = '${raw}'

[dart]
format = '\([$symbol$version]($style)\)'
symbol = 'dart:'
version_format = '${raw}'

[dotnet]
format = '\([$symbol$version(:$tfm)]($style)\)'
symbol = 'net:'
version_format = '${raw}'

[golang]
format = '\([$symbol$version(<$mod_version)]($style)\)'
symbol = 'go:'
version_format = '${raw}'

[gradle]
format = '\([$symbol$version]($style)\)'
symbol = 'gradle:'
version_format = '${raw}'

[java]
format = '\([$symbol$version]($style)\)'
symbol = 'java:'
version_format = '${raw}'

[kotlin]
format = '\([$symbol$version]($style)\)'
symbol = 'kt:'
version_format = '${raw}'

[lua]
format = '\([$symbol$version]($style)\)'
symbol = 'lua:'
version_format = '${raw}'

[nodejs]
format = '\([$symbol$version]($style)\)'
symbol = 'node:'
version_format = '${raw}'

[package]
format = '\([$symbol$version]($style)\)'
symbol = 'pkg:'
version_format = '${raw}'

[php]
format = '\([$symbol$version]($style)\)'
symbol = 'php:'
version_format = '${raw}'

[python]
format = '\([$symbol$pyenv_prefix$version(\($virtualenv\))]($style)\)'
symbol = 'py:'
version_format = '${raw}'

[rlang]
format = '\([$symbol$version]($style)\)'
symbol = 'r:'
version_format = '${raw}'

[ruby]
format = '\([$symbol$version]($style)\)'
symbol = 'rb:'
version_format = '${raw}'

[rust]
format = '\([$symbol$version]($style)\)'
symbol = 'rs:'
version_format = '${raw}'

[scala]
format = '\([$symbol$version]($style)\)'
symbol = 'scala:'
version_format = '${raw}'

[container]
format = '\([$symbol$name]($style)\)'
symbol = 'ctr:'

[os]
disabled = false
format = '\[[os:$type]($style)\]'

[battery]
format = '\[[$symbol$percentage]($style)\]'
full_symbol = 'bat100:'
charging_symbol = 'bat+:'
discharging_symbol = 'bat:'
unknown_symbol = 'bat?'
empty_symbol = 'bat0:'


[[battery.display]]
threshold = 20
style = 'bold red'
charging_symbol = 'bat+:'
discharging_symbol = 'bat:'

[[battery.display]]
threshold = 50
style = 'bold orange'
charging_symbol = 'bat+:'
discharging_symbol = 'bat:'

[[battery.display]]
threshold = 90
style = 'bold green'
charging_symbol = 'bat+:'
discharging_symbol = 'bat:'

[time]
disabled = false
format = '\[[$time]($style)\]'
